# Generated by Django 3.2.8 on 2021-10-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('sender_id', models.IntegerField(db_index=True, editable=False)),
                ('receiver_id', models.IntegerField(db_index=True, editable=False)),
                ('text', models.CharField(editable=False, max_length=400)),
                ('is_unread', models.BooleanField(default=True)),
                ('is_deleted_by_sender', models.BooleanField(default=False)),
                ('is_deleted_by_receiver', models.BooleanField(default=False)),
            ],
        ),
    ]
